package com.github.kr328.clash.common.model

enum class DiagnosticsLogEvent(
    val code: Int,
    val wireName: String,
) {
    UiEnableRequested(1, "ui_enable_requested"),
    UiEnableRejectedNotConfigured(2, "ui_enable_rejected_not_configured"),
    UiEnableRejectedEndpointMissing(3, "ui_enable_rejected_endpoint_missing"),
    UiEnableRejectedVpnStopped(4, "ui_enable_rejected_vpn_stopped"),
    UiEnableRejectedCredentialUnavailable(5, "ui_enable_rejected_credential_unavailable"),
    UiDisableRequested(6, "ui_disable_requested"),
    SettingsSaveRequested(7, "settings_save_requested"),
    SettingsSaveRejectedVpnRunning(8, "settings_save_rejected_vpn_running"),
    SettingsSaveRejectedEndpointInvalid(9, "settings_save_rejected_endpoint_invalid"),
    SettingsSaveRejectedCredentialIncomplete(10, "settings_save_rejected_credential_incomplete"),
    SettingsSaveRejectedCredentialMissing(11, "settings_save_rejected_credential_missing"),
    CredentialSaveSucceeded(12, "credential_save_succeeded"),
    CredentialSaveFailed(13, "credential_save_failed"),
    EndpointSaveSucceeded(14, "endpoint_save_succeeded"),
    CredentialDeleteRequested(15, "credential_delete_requested"),
    CredentialDeleteRejectedVpnRunning(16, "credential_delete_rejected_vpn_running"),
    CredentialDeleteSucceeded(17, "credential_delete_succeeded"),
    CredentialDeleteFailed(18, "credential_delete_failed"),
    SettingsResetCredentialsCleared(19, "settings_reset_credentials_cleared"),
    ServiceModuleStarted(20, "service_module_started"),
    ServicePendingEventsFlushed(21, "service_pending_events_flushed"),
    ServiceModeEnabled(22, "service_mode_enabled"),
    ServiceModeDisabled(23, "service_mode_disabled"),
    ServiceSessionResolved(24, "service_session_resolved"),
    ServiceSessionRejectedEndpointInvalid(25, "service_session_rejected_endpoint_invalid"),
    ServiceSessionRejectedCredentialMissing(26, "service_session_rejected_credential_missing"),
    ServiceSessionRejectedCredentialInvalid(27, "service_session_rejected_credential_invalid"),
    ServiceControllerDiagnosticsApplied(28, "service_controller_diagnostics_applied"),
    ServiceControllerLocalApplied(29, "service_controller_local_applied"),
    ServiceControllerApplyFailed(30, "service_controller_apply_failed"),
    ServiceTunnelStartRequested(31, "service_tunnel_start_requested"),
    ServiceCleanupCompleted(32, "service_cleanup_completed"),
    StateConnecting(33, "state_connecting"),
    StateReady(34, "state_ready"),
    StateConfigurationError(35, "state_configuration_error"),
    StateAccessDenied(36, "state_access_denied"),
    StateUnreachable(37, "state_unreachable"),
    NativeStartRequested(38, "native_start_requested"),
    NativeStartRejectedControllerSecret(39, "native_start_rejected_controller_secret"),
    NativeStartRejectedAuth(40, "native_start_rejected_auth"),
    NativeStartRejectedEndpoint(41, "native_start_rejected_endpoint"),
    NativeStartRejectedRemotePort(42, "native_start_rejected_remote_port"),
    NativeStartIgnoredAlreadyRunning(43, "native_start_ignored_already_running"),
    NativeClientCreated(44, "native_client_created"),
    NativeClientCreateFailed(45, "native_client_create_failed"),
    NativeTransportWorkerStarted(46, "native_transport_worker_started"),
    NativeTransportStartFailed(47, "native_transport_start_failed"),
    NativeProbeStarted(48, "native_probe_started"),
    NativeProbeReady(49, "native_probe_ready"),
    NativeProbeAccessDenied(50, "native_probe_access_denied"),
    NativeProbeUnreachable(51, "native_probe_unreachable"),
    NativeTransportStoppedExpected(52, "native_transport_stopped_expected"),
    NativeTransportStoppedUnexpected(53, "native_transport_stopped_unexpected"),
    NativeStopRequested(54, "native_stop_requested"),
    NativeStopCompleted(55, "native_stop_completed"),
    NativeStopNoop(56, "native_stop_noop"),
    Unknown(57, "unknown"),
    SettingsOpened(58, "settings_opened"),
    UiEnableCancelled(59, "ui_enable_cancelled"),
    SettingsClosed(60, "settings_closed"),
    EndpointSaveFailed(61, "endpoint_save_failed"),
    CredentialPreserved(62, "credential_preserved"),
    StateStopped(63, "state_stopped"),
    ServicePendingModeApplied(64, "service_pending_mode_applied"),
    UiModeCommandStoreFailed(65, "ui_mode_command_store_failed"),
    ServiceModeCommandAckFailed(66, "service_mode_command_ack_failed"),
    ;

    companion object {
        fun fromCode(code: Int): DiagnosticsLogEvent = entries.firstOrNull { it.code == code } ?: Unknown
    }
}
